### PR TITLE
Sub: Add support for Vectored 6DOF ROV

### PR DESCRIPTION
**Pull request by DavidIngraham**
Added support for a vectored 6DOF ROV using 4 motors in the standard vector configuration and 4 motors in the vertical direction. This is the setup used by the ASU Robosub team on our "Triton" Vehicle.

### CODE REVIEW

**Comment by DavidIngraham** [comment]
Just figured I'd check to see if you guys are interested in adding support for more frame configs on master.

If you would prefer for users to keep non-BlueROV motor configurations on their own branch then that's fine too.

**Comment by rjehangir** [comment]
David, nice work on this. I have merged it. There are a lot of potential ROV frame types so we'll have to figure out a good way to keep them all organized as the list grows.

-Rusty

**Comment by DavidIngraham** [comment]
Thanks Rusty,
I'm planning to contribute some more to get more features working and add more "flight modes".  Do you have a roadmap for changes that you're going to be making? Also, is there a good place to discuss development? Maybe on your forum or on gitter?

Also, is "Control_ROV" currently used anywhere? I'm a bit confused because flightmodes.cpp would lead me to believe that stabilized is still mapped to "Control_Stabilized"

-David

**Comment by jaxxzer** [comment]
The only supported control modes right now are stabilize and alt-hold. Control_ROV hasn't been used, it's a bit of a place holder right now.

**Comment by DavidIngraham** [comment]
Got it. Are we planning to use a similar flight mode naming scheme as Copter? This would make it easier for GCS compatibility. It seems like stabilize, acro, loiter, alt hold, etc all have analogues for an ROV.

**Comment by rjehangir** [comment]
David, I just removed the control_rov file. It's a remnant of some old work. We are going to stick with the same flight modes as Copter for now. Thanks for pointing that out. 

As far as places to discuss, it's only been a few of us so far. I just made a Gitter for discussion! Good idea.

https://gitter.im/bluerobotics/ardusub

-Rusty

**Pull request closed without merging**
