### PR TITLE
Update AP_MotorsBlueROV6DOF.cpp

### PR DESCRIPTION
**Pull request by NITHYANANDA18**

### CODE REVIEW

**Comment by jaxxzer** [comment]
If you want a new motor configuration to be merged, you must make a new configuration file, and configuration type as a build option. The BlueROV file is specifically for use with the BlueROV, these numbers should not be changed.

**Comment by NITHYANANDA18** [comment]
Hello..... Sorry if there was any inconvenience caused....

**Comment by rjehangir** [comment]
@NITHYANANDA18 - No worries. Let us know if you want to add a frame configuration.

Closing this.

**Comment by NITHYANANDA18** [comment]
Sorry for the horrible mix up....is there a way i can get firmware for the
the motor configuration i have attached below....

**Comment by rjehangir** [comment]
@NITHYANANDA18 I would recommend building the firmware in your own clone of the repository. You are welcome to do that and use the firmware. There's no need for a pull request unless you feel that the changes would benefit others.

**Comment by NITHYANANDA18** [comment]
Yeah... I understand now.... Thanks...

**Comment by NITHYANANDA18** [comment]
Can you send me the link to github file where the entire source code of
bluerov is in one place....?
Thank you..

**Comment by rjehangir** [comment]
@NITHYANANDA18 The "ArduSub" repository is the source code for the ArduSub project and has the code needed for the BlueROV. You can download a zip file from this link: https://github.com/bluerobotics/ardusub/

**Comment by NITHYANANDA18** [comment]
Thanks a lot.... Sorry again...

**Pull request closed without merging**
