### PR TITLE
Sub: Updated Correction Factors for Vectored6DOF

### PR DESCRIPTION
**Pull request by DavidIngraham**
These are the corrected factors Vectored6DOF. The other ones don’t work
at all. I forgot to push this a long time ago.

### CODE REVIEW

**Comment by rjehangir** [comment]
@DavidIngraham Thanks for the PR. Since there were lots of merges and I didn't want to dirty up the history, I just cherry-picked the two commits with the changes. It's in master.

**Comment by DavidIngraham** [comment]
Thanks Rusty, I'm still trying to get a hang of this whole rebasing workflow

**Comment by rjehangir** [comment]
No worries. Thanks for the update. By the way, since I don't have a vectored 6DOF ROV, I'm counting on you right now to keep that configuration updated. :-)

**Comment by DavidIngraham** [comment]
Sure thing. Once finals are over in a couple weeks I'll have a lot more
time to get everything tuned in. We tested the normalization code over the
weekend and it helped but it still needs improvement. I have some ideas
that I should be able to implement by mid-may.

Also, I'm going to start working on some ROS integration for visual
odometers stuff soon. As a part of that project I'm going to try to get
a SITL sim working using UWSim. We'll have to create a software later
similar to Adrucopter's Rotors simulator to support that, but I think it
will be very valuable moving forward.

**Pull request closed without merging**
